# How to use "Multi-Label Confusion Matrix" (MLCM) algorithm

Please read the following paper for more information:\
M. Heydarian, T. Doyle, and R. Samavi, MLCM: Multi-Label Confusion Matrix, 
IEEE Access, 2022

In [1]:
import numpy as np
import sklearn.metrics as skm
from mlcm import mlcm

# Creating random True and Predicted labels

In [2]:
# creating "random true" and "random predicted" labels (multi-label); 
# 1000 samples of 5 classes.
number_of_samples = 1000
number_of_classes = 5
label_true = np.random.randint(2, size=(number_of_samples, number_of_classes))
label_pred = np.random.randint(2, size=(number_of_samples, number_of_classes))

In [3]:
print('examples of True labels\n',label_true[:4])
print('examples of Predicted labels\n',label_pred[:4])

examples of True labels
 [[0 1 0 0 1]
 [1 0 1 0 1]
 [0 1 1 0 1]
 [1 0 0 0 1]]
examples of Predicted labels
 [[0 1 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]]


# Computing confusion matrix using 'MLCM"

In [4]:
conf_mat,normal_conf_mat = mlcm.cm(label_true,label_pred)

print('\nRaw confusion Matrix:')
print(conf_mat)
print('\nNormalized confusion Matrix (%):')
print(normal_conf_mat) 

MLCM has one extra row (NTL) and one extra column (NPL).        
Please read the following paper for more information:
        Heydarian et al., MLCM: Multi-Label Confusion Matrix, IEEE Access,2022        
To skip this message, please add parameter "print_note=False"
        e.g., conf_mat,normal_conf_mat = mlcm.cm(label_true,label_pred,False)

Raw confusion Matrix:
[[284  96  78  94 118  95]
 [ 75 231  89  92 103  85]
 [ 75  94 247  86 115  97]
 [ 73 104 103 251 109  69]
 [ 78  90  88  94 266  89]
 [  9  12  14  10  14   1]]

Normalized confusion Matrix (%):
[[37. 13. 10. 12. 15. 12.]
 [11. 34. 13. 14. 15. 13.]
 [11. 13. 35. 12. 16. 14.]
 [10. 15. 15. 35. 15. 10.]
 [11. 13. 12. 13. 38. 13.]
 [15. 20. 23. 17. 23.  2.]]


# Scores using MLCM

In [5]:
one_vs_rest = mlcm.stats(conf_mat)

[[[ 996  310]
  [ 481  284]]

 [[1049  396]
  [ 444  231]]

 [[1033  372]
  [ 467  247]]

 [[1029  376]
  [ 458  251]]

 [[1014  459]
  [ 439  266]]

 [[1279  435]
  [  59    1]]]

       class#     precision        recall      f1-score        weight

            0          0.48          0.37          0.42          765
            1          0.37          0.34          0.35          675
            2          0.40          0.35          0.37          714
            3          0.40          0.35          0.38          709
            4          0.37          0.38          0.37          705
          NTL          0.00          0.02          0.00          60

    micro avg          0.35          0.35          0.35          3628
    macro avg          0.34          0.30          0.32          3628
 weighted avg          0.40          0.35          0.37          3628


In [6]:
one_vs_rest = mlcm.stats(conf_mat, False)


       class#     precision        recall      f1-score        weight

            0          0.48          0.37          0.42          765
            1          0.37          0.34          0.35          675
            2          0.40          0.35          0.37          714
            3          0.40          0.35          0.38          709
            4          0.37          0.38          0.37          705
          NTL          0.00          0.02          0.00          60

    micro avg          0.35          0.35          0.35          3628
    macro avg          0.34          0.30          0.32          3628
 weighted avg          0.40          0.35          0.37          3628


In [7]:
print('\n',one_vs_rest)


 [[[ 996  310]
  [ 481  284]]

 [[1049  396]
  [ 444  231]]

 [[1033  372]
  [ 467  247]]

 [[1029  376]
  [ 458  251]]

 [[1014  459]
  [ 439  266]]

 [[1279  435]
  [  59    1]]]


# Scores using scikit-learn library

In [8]:
cm = skm.multilabel_confusion_matrix(label_true,label_pred)
print(cm)
print(skm.classification_report(label_true,label_pred))

[[[241 215]
  [260 284]]

 [[275 251]
  [243 231]]

 [[260 229]
  [264 247]]

 [[297 231]
  [221 251]]

 [[229 269]
  [236 266]]]
              precision    recall  f1-score   support

           0       0.57      0.52      0.54       544
           1       0.48      0.49      0.48       474
           2       0.52      0.48      0.50       511
           3       0.52      0.53      0.53       472
           4       0.50      0.53      0.51       502

   micro avg       0.52      0.51      0.51      2503
   macro avg       0.52      0.51      0.51      2503
weighted avg       0.52      0.51      0.51      2503
 samples avg       0.51      0.50      0.46      2503



/usr/lib/python3/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
