# Test "Multi-Label Confusion Matrix" (MLCM) algorithm

In [1]:
#     Please read the following paper for more information:
#     M. Heydarian, T. Doyle, and R. Samavi, MLCM: Multi-Label Confusion Matrix, 
#     IEEE Access, 2022

In [2]:
import numpy as np
import sklearn.metrics as skm
from MLCM import mlcm

# creating random True and Predicted labels

In [3]:
# creating "random true" and "random predicted" labels (multi-label); 
# 1000 samples of 5 classes.
number_of_samples = 1000
number_of_classes = 5
label_true = np.random.randint(2, size=(number_of_samples, number_of_classes))
label_pred = np.random.randint(2, size=(number_of_samples, number_of_classes))

In [4]:
print('examples of True labels\n',label_true[:4])
print('examples of Predicted labels\n',label_pred[:4])

examples of True labels
 [[1 0 0 1 1]
 [1 1 0 1 1]
 [0 1 0 0 1]
 [0 0 0 0 1]]
examples of Predicted labels
 [[0 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 0 1]
 [0 0 1 0 1]]


# scores using scikit-learn library

In [5]:
cm = skm.multilabel_confusion_matrix(label_true,label_pred)
print(cm)
print(skm.classification_report(label_true,label_pred))

[[[249 251]
  [254 246]]

 [[252 244]
  [252 252]]

 [[233 273]
  [266 228]]

 [[241 252]
  [268 239]]

 [[263 231]
  [238 268]]]
              precision    recall  f1-score   support

           0       0.49      0.49      0.49       500
           1       0.51      0.50      0.50       504
           2       0.46      0.46      0.46       494
           3       0.49      0.47      0.48       507
           4       0.54      0.53      0.53       506

   micro avg       0.50      0.49      0.49      2511
   macro avg       0.50      0.49      0.49      2511
weighted avg       0.50      0.49      0.49      2511
 samples avg       0.48      0.48      0.44      2511



/usr/lib/python3/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/lib/python3/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Computing confusion matrix using 'MLCM"

In [6]:
conf_mat,normal_conf_mat = mlcm.cm(label_true,label_pred)

print('\nRaw confusion Matrix:')
print(conf_mat)
print('\nNormalized confusion Matrix (%):')
print(normal_conf_mat) 

MLCM has one extra row (NTL) and one extra column (NPL).        
Please read the following paper for more information:
        Heydarian et al., MLCM: Multi-Label Confusion Matrix, IEEE Access,2022        
To skip this message, please add parameter "print_note=False"
        e.g., conf_mat,normal_conf_mat = mlcm.cm(label_true,label_pred,False)

Raw confusion Matrix:
[[246  96 104 102  92  69]
 [ 89 252 114 114 103  72]
 [ 91  88 228 111  99  75]
 [ 92 114 115 239  91  88]
 [ 95  84 112 113 268  72]
 [ 13  12  14  10  13   1]]

Normalized confusion Matrix (%):
[[35. 14. 15. 14. 13. 10.]
 [12. 34. 15. 15. 14. 10.]
 [13. 13. 33. 16. 14. 11.]
 [12. 15. 16. 32. 12. 12.]
 [13. 11. 15. 15. 36. 10.]
 [21. 19. 22. 16. 21.  2.]]


# scores using MLCM

In [7]:
one_vs_rest = mlcm.stats(conf_mat)

[[[ 988  380]
  [ 463  246]]

 [[ 982  394]
  [ 492  252]]

 [[1006  459]
  [ 464  228]]

 [[ 995  450]
  [ 500  239]]

 [[ 966  398]
  [ 476  268]]

 [[1233  376]
  [  62    1]]]

       class#     precision        recall      f1-score        weight

            0          0.39          0.35          0.37          709
            1          0.39          0.34          0.36          744
            2          0.33          0.33          0.33          692
            3          0.35          0.32          0.33          739
            4          0.40          0.36          0.38          744
          NTL          0.00          0.02          0.00          63

    micro avg          0.33          0.33          0.33          3691
    macro avg          0.31          0.29          0.30          3691
 weighted avg          0.37          0.33          0.35          3691


In [8]:
one_vs_rest = mlcm.stats(conf_mat, False)


       class#     precision        recall      f1-score        weight

            0          0.39          0.35          0.37          709
            1          0.39          0.34          0.36          744
            2          0.33          0.33          0.33          692
            3          0.35          0.32          0.33          739
            4          0.40          0.36          0.38          744
          NTL          0.00          0.02          0.00          63

    micro avg          0.33          0.33          0.33          3691
    macro avg          0.31          0.29          0.30          3691
 weighted avg          0.37          0.33          0.35          3691


In [9]:
print('\n',one_vs_rest)


 [[[ 988  380]
  [ 463  246]]

 [[ 982  394]
  [ 492  252]]

 [[1006  459]
  [ 464  228]]

 [[ 995  450]
  [ 500  239]]

 [[ 966  398]
  [ 476  268]]

 [[1233  376]
  [  62    1]]]
